# Generated by Django 3.2 on 2021-04-27 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uid', models.CharField(default='6088a1d244af19054e011a9e', max_length=200, primary_key=True, serialize=False)),
                ('rrs_url', models.TextField()),
                ('model_url', models.TextField()),
                ('max_contributor', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
                ('started_at', models.DateTimeField(verbose_name='started_at')),
                ('finished_at', models.DateTimeField(verbose_name='finished_at')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('uid', models.CharField(default='6088a1d244af19054e011a9f', max_length=200, primary_key=True, serialize=False)),
                ('credit', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('started_at', models.DateTimeField(verbose_name='started_at')),
                ('finished_at', models.DateTimeField(verbose_name='finished_at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
