# Generated by Django 3.2 on 2021-04-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='6071c21844af190be2a110b2', max_length=200)),
                ('hello', models.CharField(max_length=200)),
                ('world', models.CharField(max_length=200)),
                ('here', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
            ],
        ),
    ]
