# Generated by Django 3.2 on 2021-04-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='uid',
            field=models.CharField(default='6071c23644af190be69b9a6a', max_length=200),
        ),
    ]
