# Generated by Django 3.2 on 2021-04-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='uid',
            field=models.CharField(default='6071c38944af190c18f6c201', max_length=200),
        ),
    ]
