# Generated by Django 3.2 on 2021-04-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='f74d22d2-d279-40f5-a2cc-231c717ffde0', editable=False, max_length=200),
        ),
    ]
