# Generated by Django 3.2 on 2021-04-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_user_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='233ec0d7-4e80-4bb5-9c6a-6c23245486b4', editable=False, max_length=200, unique=True),
        ),
    ]
